config/routes.rb
SimpleTickets::Application.routes.draw do
  get "commnets/create"
  devise_for :users

  root 'issues#new'

  resources :issues do
    patch :fire
  end

  resources :comments, only: [:new, :create]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :issue
  belongs_to :user

  validates_presence_of :body

  after_save :change_issue_status

  def author
    if user.present?
      user.username
    else
      issue.reporter_name
    end
  end

  def change_issue_status
    if user.present?
      issue.staff_response!
    else
      issue.customer_response!
    end
  end

end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  include AASM

  belongs_to :user
  belongs_to :department
  has_many :comments

  validates :reporter_email, presence: true, email: true
  validates_presence_of :reporter_name, :subject, :description

  scope :unassigned, -> { where user_id: nil }
  scope :opened, -> { where 'status in (?)', %w(waiting_for_staff_response waiting_for_customer on_hold) }
  scope :closed, -> { where 'status in (?)', %w(cancelled completed) }
  scope :filtered, -> (query) { where("id = ? OR subject LIKE ?", query, "%#{query}%")}

  after_create :send_notification
  before_validation :generate_uid, on: :create

  delegate :name, to: :department, prefix: true, allow_nil: true
  #delegate :username, to: :user, allow_nil: true

  # set pagination count
  self.per_page = 10

  #def department_name
  #  department.name if department.present?
  #end

  def assigned_to
    user.username if user.present?
  end

  aasm column: 'status' do
    state :waiting_for_staff_response, initial: true
    state :waiting_for_customer
    state :on_hold
    state :cancelled
    state :completed

    event :staff_response do
      transitions from: [:waiting_for_staff_response, :waiting_for_customer], to: :waiting_for_customer
    end

    event :customer_response do
      transitions from: [:waiting_for_staff_response, :waiting_for_customer], to: :waiting_for_staff_response
    end

    event :hold do
      transitions from: [:waiting_for_staff_response, :waiting_for_customer], to: :on_hold
    end

    event :unhold do
      transitions from: :on_hold, to: :waiting_for_staff_response
    end

    event :cancel do
      transitions from: [:waiting_for_staff_response, :waiting_for_customer, :on_hold], to: :cancelled
    end

    event :complete do
      transitions from: [:waiting_for_staff_response, :waiting_for_customer, :on_hold], to: :completed
    end

  end

  def can_comment?
    (self.aasm.states(:permissible => true).include? :waiting_for_staff_response) ||
        (self.aasm.states(:permissible => true).include? :waiting_for_customer)
  end

  def possible_actions
    self.aasm.events & [:hold, :unhold, :cancel, :complete]
  end

  def send_notification
    IssueMailer.new_issue(self).deliver
  end

  def fire(event)
    self.send("#{event}!") if self.aasm.events.include? event.to_sym
  end

  private

  def generate_uid
    while true
      temp_uid = build_uid
      if ensure_uniq?(temp_uid)
        self.uid = temp_uid
        break
      end
    end
  end

  def build_uid
    # ABC-123-ABC-123AB where: ABC is random 3-char string, 123–random 3-digit number
    chars = ('A'..'Z').to_a
    numbers = (0..9).to_a
    "#{chars.sample(3).join}-#{numbers.sample(3).join}-#{chars.sample(3).join}-#{numbers.sample(3).join}#{chars.sample(2).join}"
  end

  def ensure_uniq?(uid)
    Issue.find_by_uid(uid).blank?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :issues

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :username, :first_name, :last_name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:username, :first_name, :last_name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:sign_in) do |u|
      u.permit(:username, :password)
    end
  end

  def after_sign_in_path_for(resource)
    issues_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_issue

  def create
    @comment = Comment.new comment_params
    @comment.user = current_user if user_signed_in?

    if @comment.save
      redirect_to @issue, notice: 'Comment was successfully added.'
    else
      redirect_to @issue, warn: 'Error has been occurred on adding comment.'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:issue_id, :user_id, :body)
  end

  def set_issue
    @issue = Issue.find(params[:comment][:issue_id])
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :update]
  before_filter :authenticate_user!, only: [:index]

  has_scope :unassigned, :type => :boolean
  has_scope :opened, :type => :boolean
  has_scope :on_hold, :type => :boolean
  has_scope :closed, :type => :boolean
  has_scope :filtered

  def index
    # where('1=1') used instead of .all to avoid rails 4 deprecation warning
    # see https://github.com/plataformatec/has_scope/issues/41
    @issues = apply_scopes(Issue).paginate(:page => params[:page])
  end

  def show
    @comment = Comment.new
    @comment.user = current_user if user_signed_in?
    @comment.issue = @issue
  end

  def new
    @issue = Issue.new
  end

  def create
    @issue = Issue.new(issue_params)

    if @issue.save
      redirect_to @issue, notice: 'Issue was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @issue.update(issue_params)
      redirect_to @issue, notice: 'Issue was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def fire
    @issue = Issue.find(params[:issue_id])
    @issue.fire(params[:event]) if @issue.present?
    redirect_to @issue
  end

  private

  def set_issue
    @issue = Issue.find(params[:id])
  end

  def issue_params
    params.require(:issue).permit(:reporter_name, :reporter_email, :department_id,
                  :subject, :description, :user_id )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commnets_helper.rb
module CommnetsHelper
end

app/helpers/issue_helper.rb
module IssueHelper
end

app/views/comments/_comment.html.slim
.row
  strong = comment.author
  i
    | &nbsp;at:&nbsp;
    = comment.created_at
  p = comment.body

app/views/comments/_form.html.slim
.well
  = form_for @comment, html: { role: 'form' } do |f|
    = f.hidden_field :issue_id
    .form-group
      | Leave your comment
      = f.text_area :body, class: 'form-control'
    button#submit_comment.btn.btn-primary type="submit"
      | Submit

app/views/commnets/create.html.slim
h1 Commnets#create
p Find me in app/views/commnets/create.html.slim

app/views/issues/index.html.slim
.container
  h3 Issues
  div
    table#issues_list.table.table-striped
      thead
        th #
        th Subject
        th Reporter
        th Status
      tbody
        - @issues.each do |i|
          = content_tag_for :tr, i
            td = link_to i.uid, issue_path(i)
            td = link_to i.subject, issue_path(i)
            td
              = i.reporter_name
              | &nbsp;
              i = i.reporter_email
            td = i.status
  == will_paginate @issues, renderer: BootstrapPagination::Rails

app/views/issues/new.html.slim
.container
  h3 New issue
  = form_for @issue, html: {role: 'form'} do |f|
    .form-group
      = f.label :reporter_name
      = f.text_field :reporter_name, class: 'form-control'
    .form-group
      = f.label :reporter_email
      = f.text_field :reporter_email, class: 'form-control'
    .form-group
      = f.label :department
      = f.collection_select :department_id, Department.all, :id, :name, { prompt: 'Please select department' }, { class: 'form-control' }
    .form-group
      = f.label :subject
      = f.text_field :subject, class: 'form-control'
    .form-group
      = f.label :description
      = f.text_area :description, class: 'form-control'
    button.btn.btn-primary type="submit"
      | Submit

app/views/issues/show.html.slim
.container
  h3
   | Issue #
   = @issue.uid
  .row
    == render 'shared/issue_actions'
  div#issue_details
    .row
      .col-md-10
        .row
          .col-md-2
            strong Reporter name:
          .col-md-4
            = @issue.reporter_name
        .row
          .col-md-2
            strong Reporter email:
          .col-md-8
            = @issue.reporter_email
        .row
          .col-md-2
            strong Department:
          .col-md-8
            = @issue.department_name
        .row
          .col-md-2
            strong Assigned to:
          .col-md-8
            = @issue.assigned_to
        .row
          .col-md-2
            strong Status:
          .col-md-8
            = @issue.status
        .row
          .col-md-2
            strong Subject
          .col-md-8
            = @issue.subject
        .row
          .col-md-2
            strong Description
          .col-md-8
            = simple_format @issue.description

    .row
      -if @issue.comments.any?
        #comments_container.well
          h4 Comments
          == render partial: 'comments/comment', collection: @issue.comments
    .row
      - if @issue.can_comment?
        == render 'comments/form', locals: {issue: @issue}
    .row
      - if user_signed_in?
        = link_to 'Back to issues list', issues_path

app/views/issues/thank_you.html.slim
.container
  h3 Thank you to help as to make our product better
  p
    | If you want to create another issue, click
    = link_to 'here', new_issue_path

app/views/layouts/_login.html.slim
li
  - if user_signed_in?
    p.navbar-text
      | Logged as: &nbsp;
      = current_user.email
      | &nbsp;
      = link_to 'Log Out', destroy_user_session_path, method: :delete
  - else
    = link_to 'Log In', new_user_session_path

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name == :notice ? "success" : "danger"}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        - if user_signed_in?
          == render 'layouts/navigation_links'
      ul.nav.navbar-nav.navbar-right
        == render 'layouts/login'

app/views/layouts/_navigation_links.html.slim
li = link_to 'All Issues', issues_path
li = link_to 'Unassigned', issues_path(unassigned: true)
li = link_to 'Opened', issues_path(opened: true)
li = link_to 'On Hold', issues_path(on_hold: true)
li = link_to 'Closed', issues_path(closed: true)
= form_tag issues_path, method: :get, class: 'navbar-form navbar-left', role: 'search' do
  .form-group
    = text_field_tag :filtered, nil, placeholder: 'Search...', class: 'form-control'
  button#search_button.btn.btn-default type="submit" Submit

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Simple Tickets'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Simple Tickets'}"
    == stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true
    == javascript_include_tag "application", "data-turbolinks-track" => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/shared/_issue_actions.html.slim
- if user_signed_in?
  .col-md-4
    .btn-group
      - @issue.possible_actions.each do |a|
        button.btn.btn-default type="button"
          = link_to a.to_s, issue_fire_path(@issue, event: a), method: :patch, class: 'btn-link default-link'
  .col-md-4
    = form_for @issue, method: :patch, html: { class: 'form-inline', role: 'form' } do |f|
      button.btn.btn-default type="submit"
        | Assign to:
      .form-group
        = f.collection_select :user_id, User.all, :id, :username, { promt: 'Please select assignee'}, { class: 'form-control'}